### PR TITLE
Add steam to Brewfile

### PR DESCRIPTION
**Pull request by nickwu241**
@rchatrath7 please review!

FYI @qipanda

### CODE REVIEW

**Comment by nickwu241** [comment]
Good catch! Thank you, that's why 👀 are always good. Ready for review again! 😄

**Review by rchatrath7 — APPROVED** [review]
LTGM assuming:  
- [ ] I have updated documentation if I changed a job's output or a public API/feature
- [ ]  I have tested my changes locally
- [ ]  I have 🎩'd these changes in the following ways:

**Comment by nickwu241** [comment]
Sounds good, thank you for the quick review! Gonna 🐑🇮🇹

**Comment by nickwu241** [comment]
After opening steam, it updates and then shows this screen
image

**Pull request merged**
